# .portfolio/config.yml
name: Shelf Scanner
slug: shelf-scanner
description: >
  A book identification and recommendation system that uses AI to analyze bookshelf images and provide personalized recommendations.
tech_stack:
  - LangChain
  - LangGraph
  - Gemini AI
  - FastAPI
  - Vite
  - TypeScript
  - Tailwind CSS
  - Docker
  - Render
tags:
  - GenAI
  - Full-Stack
  - Rate Limiting
live_url: https://shelf-scanner.onrender.com/
repo_url: https://github.com/Namasivaayam-L/shelf-scanner
thumbnail: https://raw.githubusercontent.com/Namasivaayam-L/shelf-scanner/main/.portfolio/coverr.png
readme_path: README.md
created_at: 2025-09-18
updated_at: 2025-11-20
featured: true
is_active: true